/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.gretty") version "4.1.5"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}
description = "CometD Server for Bayeux Protocol"

dependencies {
    api(libs.org.cometd.java.cometd.java.api.server)
    api(libs.org.cometd.javascript.cometd.javascript.common)
    api(libs.org.cometd.java.cometd.java.server.http.jakarta)
    api(libs.org.cometd.java.cometd.java.server.websocket.jakarta)
    api(libs.org.eclipse.jetty.jetty.jmx)
    api(libs.org.eclipse.jetty.ee10.jetty.ee10.servlets)
    api(libs.org.eclipse.jetty.jetty.slf4j.impl)
    api(libs.org.eclipse.jetty.jetty.util)
    api(libs.org.eclipse.jetty.jetty.util.ajax)
    compileOnly(libs.jakarta.servlet.jakarta.servlet.api)
}

group = "io.truthencode.poc"
version = "1.0-SNAPSHOT"
description = "cometd-es6"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
